### ISSUE TITLE
q: what's your use-case?

### ISSUE THREAD

**Issue by andreineculau** [cytopia/aws-export-profile#3]
I just saw this repo linked in @quinnypig's last-week-in-aws newsletter and I'm wondering what is your use-case to read the aws-cli credentials alone, as opposed to exposing the credentials aws-cli may create e.g. a session token?

I'm thinking of my team's setup which is role-driven (an IAM user only has the permission to do some password/mfa setup and assume a role --- [more here](https://cloudonaut.io/improve-aws-security-protect-your-keys-with-ease/) ) thus session token handling are a must. But your script only reads the session token if it is are stored in a profile afaics. Am I wrong?

FWIW Our script (it's actually a shell function to get around the need to `$(...)` like you do) [looks like this](https://github.com/tobiipro/support-firecloud/blob/master/bin/aws-iam-login.inc.sh) in combination with [an ugly=hackish script to extract the credentials](https://github.com/tobiipro/support-firecloud/blob/master/bin/aws-get-cli-sts).

**Comment by cytopia** [comment]
I usually use [aws-adfs](https://github.com/venth/aws-adfs) to log into a variety of different AWS accounts and then run containers locally that require access to a specific account. This tool let me quickly *enable* a profiled account for use with containers.

See the Readme with the Docker example. I will also dig into the links you have provided.

**Comment by cytopia** [comment]
@andreineculau I hope this has answered your question and I will close this issue. If not, please add anything unclear and I will re-open.
